// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXo4MVu6XkztrNDjQU3DsOvyRzvMCj8s',
    appId: '1:542937292769:web:7fc7e8fdade4b69c12fca0',
    messagingSenderId: '542937292769',
    projectId: 'search-engine-flutter',
    authDomain: 'search-engine-flutter.firebaseapp.com',
    storageBucket: 'search-engine-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe51ThOqUzKBzyNXc-qjZzPIAkPuvNrM0',
    appId: '1:542937292769:android:28d773958c8128dc12fca0',
    messagingSenderId: '542937292769',
    projectId: 'search-engine-flutter',
    storageBucket: 'search-engine-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-00UV5ZF0IfMuHYQAjahdAq8FATwDXk',
    appId: '1:542937292769:ios:db8ee1b4239597be12fca0',
    messagingSenderId: '542937292769',
    projectId: 'search-engine-flutter',
    storageBucket: 'search-engine-flutter.firebasestorage.app',
    iosBundleId: 'com.example.searchEngineFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-00UV5ZF0IfMuHYQAjahdAq8FATwDXk',
    appId: '1:542937292769:ios:db8ee1b4239597be12fca0',
    messagingSenderId: '542937292769',
    projectId: 'search-engine-flutter',
    storageBucket: 'search-engine-flutter.firebasestorage.app',
    iosBundleId: 'com.example.searchEngineFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXo4MVu6XkztrNDjQU3DsOvyRzvMCj8s',
    appId: '1:542937292769:web:8f008a3a8e9c146b12fca0',
    messagingSenderId: '542937292769',
    projectId: 'search-engine-flutter',
    authDomain: 'search-engine-flutter.firebaseapp.com',
    storageBucket: 'search-engine-flutter.firebasestorage.app',
  );
}
